name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Updated to match your project's Python version

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Build and run Streamlit app
        run: |
          streamlit run app.py &
          sleep 10  # Give the app some time to start up

      - name: Capture Streamlit output
        run: |
          mkdir -p build
          wget -O build/index.html http://localhost:8501

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
